update

diff --git a/bg-tasks/slipstream-tasks-backend b/bg-tasks/slipstream-tasks-backend
--- a/bg-tasks/slipstream-tasks-backend
+++ b/bg-tasks/slipstream-tasks-backend
@@ -729,37 +729,6 @@ if grep -q 'Display=0' /etc/mmdvmhost ; then
     sed -i 's/Display=0/Display=None/g' /etc/mmdvmhost
 fi
 
-# func to fix stuck updates
-if [ ! -f '/usr/local/sbin/wpsd-update' ]; then
-    curl -s -A "sbin-phix $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
-fi
-if grep -q "DVMEGA H" /etc/pistar-release ; then
-    curl -s -A "sbin-fw-phix $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
-fi
-if grep -q ":v" /etc/pistar-release ; then
-    curl -s -A "sbin-modem_ver-phix $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
-fi
-diag_file="/usr/local/sbin/.wpsd-diags"
-if [ -f "$diag_file" ]; then
-    # Check if the file is a text file
-    if file "$diag_file" | grep -q "text"; then
-        # Search for the string "getDVModemFirmware" in the file
-        if grep -q "getDVModemFirmware" "$diag_file"; then
-	    curl -s -A "sbin-modem_ver-phix $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
-        fi
-    fi
-fi
-sysch_file="/usr/local/sbin/.wpsd-sys-cache"
-if [ -f "$sysch_file" ]; then
-    # Check if the file is a text file
-    if file "$sysch_file" | grep -q "text"; then
-        # Search for the string "getDVModemFirmware" in the file
-        if grep -q "D2RG_MMDVM_HS" "$sysch_file"; then
-	    curl -s -A "sbin-modem_ver-phix $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
-        fi
-    fi
-fi
-
 # grab and cache latest WPSD hash
 gitFolder="/var/www/dashboard"
 gitRemoteURL=$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git config --get remote.origin.url)
@@ -857,42 +826,34 @@ EOL
 fi
 
 # 5/27/23: Bootstrapping backend scripts
-if grep -q LOGNDROP /etc/iptables.rules ; then
-   FW=true
-fi
-REPO_PATH="/usr/local/sbin"
-API_URL="https://wpsd-swd.w0chp.net/api/v1/repos/WPSD-SWD/WPSD-Scripts/branches"
-LOCAL_HASH=$(cd "$REPO_PATH" && git rev-parse master)
-REMOTE_HASH=$(curl -A "Slipstream-Task (server-side) sbin hash check $uaStr" -Ls "$API_URL" | jq -r '.[] | select(.name == "master") | .commit.id')
-if [[ "$LOCAL_HASH" != "$REMOTE_HASH" ]]; then
-    echo "The local repository is updating...."
-    curl -s -A "Script Reset Forced $uaStr" -Ls https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/reset-wpsd-sbin | sudo bash > /dev/null 2>&1
+repo_path="/usr/local/sbin"
+cd "$repo_path" || { echo "Failed to change directory to $repo_path"; exit 1; }
+git update-index --no-assume-unchanged pistar-upnp.service # get rid of legacy index not that upnp rules are in /etc/wpsd-upnp-rules
+if env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="sbin check ${gitUaStr}" git fetch origin; then
+    commits_behind=$(git rev-list --count HEAD..origin/master)
+    if [[ $commits_behind -gt 0 ]]; then
+        if env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="sbin update bootstrap ${gitUaStr}" git pull origin master; then
+	    echo "Local sbin repository updated successfully. Restarting script..."
+	    # check if user already has firewall disabled, and if so, ensure it's kept that way.
+	    if ! grep -q LOGNDROP /etc/iptables.rules ; then
+		/usr/local/sbin/wpsd-system-manager -dfw > /dev/null 2>&1
+	    else
+		/usr/local/sbin/wpsd-system-manager -efw > /dev/null 2>&1
+	    fi
+	    rm -rf /var/run/wpsd-slipstream-tasks
+	    exec bash /usr/local/sbin/.wpsd-slipstream-tasks
+	    exit
+	else
+	    echo "Failed to update the local sbin repository."
+	    exit 1
+ 	fi
+    else
+	echo "Local sbin repository is up to date."
+    fi
 else
-    echo "The local repository is up-to-date."
-    cd "$REPO_PATH"
-    git update-index --no-assume-unchanged pistar-upnp.service # get rid of legacy index not that upnp rules are in /etc/wpsd-upnp-rules
-    git reset --hard origin/master
-    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="Scripts update bootstrap ${gitUaStr}" git pull origin master
-    git reset --hard origin/master
+    echo "Failed to fetch from the remote repository."
+    exit 1
 fi
-if [ "$FW" == "true" ] ; then
-    /usr/local/sbin/wpsd-system-manager -efw > /dev/null 2>&1
-else
-    /usr/local/sbin/wpsd-system-manager -dfw > /dev/null 2>&1
-fi
-
-if [ ! -d "/usr/local/bin" ] ; then
-    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD binary installer (server-side) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Binaries.git /usr/local/bin
-    wpsd-services restart
-fi
-binsize=$(du -s /usr/local/bin | awk '{print $1}')
-if [ "$binsize" -lt 63256 ]; then
-    rm -rf /usr/local/bin
-    GIT_HTTP_CONNECT_TIMEOUT="10" GIT_HTTP_USER_AGENT="WPSD binary installer (server-side) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Binaries.git /usr/local/bin
-    wpsd-services restart
-fi
-
-cd /usr/local/bin && git reset --hard origin/master && env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="Binaries update bootstrap ${gitUaStr}" git pull origin master
 
 rm -rf /var/run/wpsd-slipstream-tasks
 
